### ISSUE TITLE
Sourcing of the ochin-CM4 board

### ISSUE THREAD

**Issue by careyer** [ochin-space/ochin-CM4#1]
Hi there,

very impressive carrier board I must say! Kudos!
Is there already a manufacturer to buy the board from or is there a way to get my hands on a test unit?
Best regards from the Open.HD project 

Cheers!
Thomas

**Comment by pernicious-flier** [comment]
Thanks careyer, i will organize a groupbuy to fabricate a number of board, i'll let you know!
