### ISSUE TITLE
Anyway to get the Gerber and BOM?

### ISSUE THREAD

**Issue by villivateur** [ochin-space/ochin-CM4#8]
Hello, it is hard to buy board from seeedstudio or any other provider in my country. But I really want to use this board.

Luckily, it is very cheap for me to make a PCB, and I have all the tools to do SMT. So, can I get the Gerber and BOM file? If so, I can make the board myself. I do not need the hardware source file at all, but only the production file.

**Comment by richard-scott** [comment]
I would assume that without offering up the required KiCad files, the project isn't truly Open Source, and the GPLv3 licence under which it is distributed is being violated.

**Comment by raphaelscholle** [comment]
The gpl licence is for the files in this github, meaning documentation and such. You do not need to make everyting opensource if you don't want to. The actual hardware is closed source. That's also not unusual, since often NDA'S and such things are required to make Hardware.

Nowhere is stated that this is an opensource hardware project. But sure, try to get any mobile phone manufacturer to release their hardware open source, since it use opensource software.

**Comment by richard-scott** [comment]
@raphaelscholle, you are on the right track, as the GPL covers all the files in the Github Repo.

The fact that it is distributed with a GPL license means it is Open Source. **Anything** in the Repo needs to have source files available to allow modification. If the project wants to restrict elements of the distribution then the GPL is not the license for the project.

And no, I would not expect a mobile phone manufacturer to release their hardware as open source. However, I doubt you'd find their schematics online in a repo on GitHub covered by a GPL license.

In the GPL it states the following:

>   1. Source Code.
> 
>   The "source code" for a work means the preferred form of the work
> for making modifications to it.  "Object code" means any non-source
> form of a work.

So, that defines "source code" as the files required to make modifications, and object code is another output generated by the source code files. PCB Schematics in PDF format are "Object code", as these can't be modified without having the preferred format source files.

A bit further down, it also defines what you need to provide for Object code:

>   The "Corresponding Source" for a work in object code form means all
> the source code needed to generate, install, and (for an executable
> work) run the object code and to modify the work, including scripts to
> control those activities.

So, in this Repo (and [this](https://github.com/ochin-space/ochin-CM4v2) one), the Source code files for your Object code are the KiCad project files. [Other](https://github.com/TwentyTwoHW/portal-hardware) Open Source Hardware projects distributed under GPL provide these files.

**Comment by pernicious-flier** [comment]
> Hello, it is hard to buy board from seeedstudio or any other provider in my country. But I really want to use this board.
> 
> Luckily, it is very cheap for me to make a PCB, and I have all the tools to do SMT. So, can I get the Gerber and BOM file? If so, I can make the board myself. I do not need the hardware source file at all, but only the production file.

I thank you Villivateur for your opinion about the project, I am glad you like it. It was out of stock for a while because it was in testing/production v2 which has many more features and now it is available in stock.
To answer your question, unfortunately, no, I do not release design sources.

**Comment by pernicious-flier** [comment]
Thanks for the discussion guys, now it takes a lawyer even to post on github :)
Anyway I clarified everything about the license of this repo and that of the ochin_cm4v2 in the README.md, I hope everything is clear now.
Have fun with the ochin! Best, Fla
